### ISSUE TITLE
サポートツールで使う言語・フレームワークを決定する

### ISSUE THREAD

**Issue by takenokoroid** [takenokoroid/new-support-tools#1]
# 概要
まだ使う言語・フレームワークが決定していなかったので決定したい
モダンフレームワークを使いたいという思い

## 目的
フレームワークを決めて開発着手できる状態にしたい

## タスク
- [x] @ifhito @takenokoroid でMTG

## 備考
候補はReact, Vueか
この規模なら正直どっちも大差ないので二人の経験値で決めるかなと思う

**Comment by ifhito** [comment]
サンクス
NextやNuxtもありかなと。

**Comment by takenokoroid** [comment]
コメントあざっす
今度のMTGできめますか

かんばんも（作っただけ
https://github.com/users/takenokoroid/projects/1/views/1
